name: CI

on:
  push:
    branches: [master]

env:
  BUCKET: bucket-name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.x
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: yarn install
    
    - name: Run tests
      run: yarn test --watchAll false
      
    - name: Build
      run: yarn build
    
    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      
    - name: Upload file to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
    
    - name: Allow public access
      run: gsutil -m acl ch -R -u Allusers:R gs://"$BUCKET"
    
    # Set cache meta for static files
    - name: Set Cache-control
      run: gsutil -m setmeta -h "Cache-control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}
    
    # Set cache meta for index.html
    - name: Set Cache-control
      run: gsutil setmeta -h "Cache-control:no-cache, no-store" gs://"$BUCKET"/index.html
    
